# name overrides
#nameOverride: ""
#fullnameOverride: ""

image:
  # If empty the application version of the chart will be used as the version for the images
  versionOverride: ""
  # The image repository or prefix for the images. For example the repository="ocir.microstream.one/" then
  # the resulting image will be "ocir.microstream.one/"
  # NOTE: The trailing slash is required if not set to an empty string
  repository: ocir.microstream.one/

# The storage node statefulset runs the eclipse-store backed user-application as the storage-nodes
storageNode:
  replicas: 2

# The proxy deployment forwards read requests to the storage-node service and write requests to the writer-proxy service
proxy:
  replicas: 1

# PVC specifications for containing the user application jar used by the storage and master-nodes
userApp:
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M

# PVC specifications for containing the storage backups used by the storage and master-nodes
storageBackups:
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M

# PVC specifications for containing the masternode storage used by the master-node
masterNodeStorage:
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M
